"""Creacion de perfil

Revision ID: 0d70c5e1acd6
Revises: a40dbbb96aa1
Create Date: 2023-09-05 15:34:36.360301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d70c5e1acd6'
down_revision = 'a40dbbb96aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
