"""Fix avatar

Revision ID: 141c9c174fd1
Revises: 0d70c5e1acd6
Create Date: 2023-09-05 17:57:50.430792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '141c9c174fd1'
down_revision = '0d70c5e1acd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_filename', sa.String(length=120), nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('avatar_filename')

    # ### end Alembic commands ###
