"""Add bcrypt password hash column

Revision ID: 47ac7b97249f
Revises: 55e5b0c6b0dd
Create Date: 2023-11-08 21:52:03.314807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ac7b97249f'
down_revision = '55e5b0c6b0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bcrypt_password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('bcrypt_password_hash')

    # ### end Alembic commands ###
