"""Added date_registered to Usuario model

Revision ID: 55e5b0c6b0dd
Revises: 141c9c174fd1
Create Date: 2023-10-04 02:29:49.075776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e5b0c6b0dd'
down_revision = '141c9c174fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('date_registered')

    # ### end Alembic commands ###
